-- Singularity AGI Platform: Core Schema (Supabase/PostgreSQL)
-- This schema powers the platform itself (https://agi-app-builder.netlify.app/)

-- 1. Projects: Stores all applications generated by the AGI
CREATE TABLE IF NOT EXISTS projects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    prompt TEXT NOT NULL,
    blueprint JSONB, -- The Architect's JSON output
    github_url TEXT,
    deploy_url TEXT,
    deploy_platform TEXT DEFAULT 'netlify',
    status TEXT DEFAULT 'pending', -- pending, building, healing, live, failed
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    feedback TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Build Logs: Stores real-time logs for every project build
CREATE TABLE IF NOT EXISTS build_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    type TEXT DEFAULT 'info', -- info, success, warning, error
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Monitoring Data: Tracks live health of deployed apps
CREATE TABLE IF NOT EXISTS monitor_data (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    status TEXT NOT NULL,
    latency_ms INTEGER,
    last_check TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Secure Vault (Optional/Encrypted): Stores user-provided API keys
CREATE TABLE IF NOT EXISTS vault (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID, -- For multi-user support
    key_name TEXT NOT NULL, -- e.g., 'OPENROUTER_API_KEY'
    encrypted_key TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
